services:
  vuejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]

volumes:
  pgdata: